# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.0

install:
  - sudo apt-get install php-pear libyaml-dev
  - sudo pecl install yaml -y

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: php vendor/bin/phpunit tests/


# Customize when the notification emails are sent.
notifications:
    email: true